### ISSUE TITLE
Fix (composite) foreign key constraint 

### ISSUE THREAD

**Issue by kevinlang** [warmwaffles/exqlite#103]
For the `:composite_foreign_key` tag, we fail due to the child table FK to the parent table being generated like so:

```
CREATE TABLE composite_child (id INTEGER PRIMARY KEY, parent_key_id INTEGER, parent_id INTEGER CONSTRAINT composite_child_parent_id_fkey REFERENCES composite_parent(id));
```

Which is completely dropping the other key.

It should instead be something like:
```
CREATE TABLE composite_child2 (id INTEGER PRIMARY KEY, parent_key_id INTEGER, parent_id INTEGER, FOREIGN KEY(parent_key_id, parent_id) REFERENCES composite_parent(key_id, id));
```

**Comment by warmwaffles** [comment]
@kevinlang I have a fix for that to generate the "correct" sql but the error we run in to is

```
foreign key on parent_id should reference only one column of table composite_parent
```

The SQL generated

```
CREATE TABLE composite_child (
id INTEGER PRIMARY KEY, 
parent_key_id INTEGER, 
parent_id INTEGER CONSTRAINT composite_child_parent_id_fkey 
    REFERENCES composite_parent(id,key_id)
)
```

formatting added by me

**Comment by warmwaffles** [comment]
From the test, here is the SQL run for the migration

```
CREATE TABLE composite_parent (id INTEGER PRIMARY KEY, key_id INTEGER)
CREATE UNIQUE INDEX composite_parent_id_key_id_index ON composite_parent (id, key_id)
CREATE TABLE composite_child (id INTEGER PRIMARY KEY, parent_key_id INTEGER, parent_id INTEGER CONSTRAINT composite_child_parent_id_fkey REFERENCES composite_parent(id,key_id))
```

**Comment by warmwaffles** [comment]
Added a fix for the reference generation here 2c4a7aef7dee45913ce2d645edd443a6c04518aa

**Comment by kevinlang** [comment]
Yeah for composite foreign key we have to use the `FOREIGN KEY(a,b) REFERENCES` syntax.

https://sqlite.org/foreignkeys.html#fk_composite

**Comment by kevinlang** [comment]
So it should be something like:
```
CREATE TABLE composite_child (
  id INTEGER PRIMARY KEY, 
  parent_key_id INTEGER, 
  parent_id INTEGER
  FOREIGN_KEY(parent_id, parent_key_id) REFERENCES composite_parent(id,key_id)
)
```

**Comment by warmwaffles** [comment]
Ah having the foreign key directive at the end and not inline with the column definition.

**Comment by warmwaffles** [comment]
This is going to be tricky to support, as we have to put the `FOREIGN KEY` part at the end of the table creation. It can not be mixed in to the definition willy nilly.

**Comment by warmwaffles** [comment]
We should probably modify the `def execute_ddl({:create, %Table{} = table, columns})` to append all compound foreign key definitions there.
