### ISSUE TITLE
Support Ecto.Adapters.SQL.Connection explain_query callback

### ISSUE THREAD

**Issue by kevinlang** [warmwaffles/exqlite#108]
No tests for this exist in `ecto` or `ecto_sql`, but it would be something nice to have.

```
  Executes an EXPLAIN query or similar depending on the adapter to obtains statistics of the given query.
```

https://www.sqlite.org/eqp.html

**Comment by kevinlang** [comment]
Doh, we have this :facepalm:

**Comment by warmwaffles** [comment]
Does it work though? @kevinlang
