### ISSUE TITLE
Description on hex.pm should include "adapter"

### ISSUE THREAD

**Issue by OldhamMade** [warmwaffles/exqlite#110]
Firstly, thanks for open-sourcing this library! SQLite is a great database, especially for smaller applications, and it seems crazy to not have an ecto3 adapter for it in the standard Ecto library.

In order to improve discoverability of this library for the community, I would like to suggest that the description on hex.pm be changed from:

> An Sqlite3 Elixir library.

to:

> An SQLite3 Elixir library with adapter for Ecto3

**Comment by warmwaffles** [comment]
Yea I'll make that change real quick. I have been mulling over the idea of making another package that is just the adapter part to keep this strictly to sqlite.

> seems crazy to not have an ecto3 adapter for it in the standard Ecto library.

@kevinlang  is working on getting this inline with `ecto_sql`'s tests and possibly getting it in upstream.

**Comment by warmwaffles** [comment]
Thanks for the suggest @OldhamMade
