### ISSUE TITLE
Repo.delete_all does not return number of affected rows

### ISSUE THREAD

**Issue by kevinlang** [warmwaffles/exqlite#35]
Simple case in my `kcl-delete-2` branch:

```
  describe "delete" do
    test "delete_all" do
      TestRepo.insert!(%Product{name: "hello"})
      assert [_] = TestRepo.all(Product)

      assert {1, _} = TestRepo.delete_all(Product)
      assert [] == TestRepo.all(Product)
    end
  end
```

The match on {1, _} will always fail.

**Comment by warmwaffles** [comment]
@kevinlang in https://github.com/warmwaffles/exqlite/pull/36 I added a `total_changes` call. We could incorporate a fix there too.

**Comment by warmwaffles** [comment]
Went ahead and made that fix, removed `total_changes` and added two tests similar to the one you posted.

**Comment by warmwaffles** [comment]
Fixed this issue
