### ISSUE TITLE
Database busy error

### ISSUE THREAD

**Issue by warmwaffles** [warmwaffles/exqlite#42]
@kevinlang I am going to track the database busy issue here.

Previous discussions:

* https://github.com/warmwaffles/exqlite/pull/38
* https://github.com/warmwaffles/exqlite/pull/39#issuecomment-792447244

**Comment by warmwaffles** [comment]
I need to dig into `Ecto.Adapters.SQL.Sandbox` more to ascertain if it can work with sqlite's restriction of 1 writer at a time. We are definitely hitting some issues where another test has opened a transaction but has not committed it yet and we are trying to read back those changes.

Yay for concurrency issues.

**Comment by kevinlang** [comment]
It is worth noting that the tests are running sequentially, and that the sandbox makes it so one checks out only a single connection at a time. So the issue we are hitting in our tests is more sequential than a real world scenario.

I think you are right that there is some issue where a sandboxed connection is not closing out correctly, affecting the other tests.

One other approach I thought of was to run tests against an in-memory database. At "checkout" time we would clone the on-disk database into a `:memory:` one. There we don't have to worry about cleanup or anything, assuming check-in drops the "connection" and thus the in-memory database.

However, I kind of like that the current way the sandbox does it, with transaction, raises these trickier transaction issues in our test suite, which perhaps reflect the real world a bit more than the memory approach.

**Comment by warmwaffles** [comment]
> However, I kind of like that the current way the sandbox does it, with transaction, raises these trickier transaction issues in our test suite, which perhaps reflect the real world a bit more than the memory approach.

This is precisely why I strayed away from using `:memory:` for integration tests.

Perhaps, instead of just returning `{:error, "Database busy"}` we can retry the statement again after a random wait?

https://github.com/warmwaffles/exqlite/blob/98dade3a5996d6930e3928eba6501a60e112db1e/lib/exqlite/connection.ex#L291-L292

**Comment by warmwaffles** [comment]
The current test error originates from this line

https://github.com/warmwaffles/exqlite/blob/98dade3a5996d6930e3928eba6501a60e112db1e/lib/exqlite/sqlite3.ex#L105

I changed it to 

```elixir
:busy -> fetch_all(conn, statement)
```

And it just hung there

```
23:06:33.422 [error] Exqlite.Connection (#PID<0.434.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.703.0> timed out because it queued and checked out the connection for longer than 15000ms
```

**Comment by warmwaffles** [comment]
For future reference, https://sqlite.org/c3ref/busy_handler.html we could provide some tooling for handling busy callbacks. Though I don't know how just yet.

**Comment by kevinlang** [comment]
One approach that may be worthwhile is moving some of the multistep logic into the NIF. :thinking:

**Comment by kevinlang** [comment]
This was an interesting read. I'm still not sure why we are getting the lock, but it looks like we can improve reliability generally by responding to a busy response by doing appropriate rollbacks/resets.

https://sqlite.org/forum/forumpost/d2d81b46bc?t=c&unf&hist

**Comment by warmwaffles** [comment]
> One approach that may be worthwhile is moving some of the multistep logic into the NIF.

So the rationale that I used for doing the individual stepping in elixir rather than the NIF is that if you have multiple database connections open where the stepping takes some time to complete, it could block the dirty nif scheduler. I wanted to allow make it return as fast as possible and to play nice with other dirty nifs.

**Comment by warmwaffles** [comment]
@kevinlang I've been mucking around with potentially doing a multistep, I just remembered why I didn't port it from esqlite.

Due to the nature of how sqlite3 has you step through the results you can encounter an `SQLITE_BUSY` in the middle of the stepping. You would have a partial set of rows to return to elixir along with conveying that it's busy. I don't think it would be wise to sleep the nif call.

**Comment by warmwaffles** [comment]
Question though. Why should we use `Ecto.Adapters.SQL.Sandbox`? When I disable sandboxing I don't run into a busy error.

**Comment by kevinlang** [comment]
The main reason to use the Sandbox is so that the changes done during tests are rolled back. That is especially important with testing something that has a unique constraint, for example. Test run 1 would succeed, but test run 2 would fail because something exists there.

Or more usually, within a single test run, test A could modify something that effects test B.

**Comment by kevinlang** [comment]
The fact that you don't hit the busy error without the sandbox, though, indicates that the issue may be with our transaction logic, since all the sandbox adds is wrapping all tests in a transaction. Since in both cases the tests run serially and should in theory not be hitting any sort of busy issue (as there is no concurrency). 

Maybe next up is to add more investigation around our transaction logic with the minimal repo we have

**Comment by kevinlang** [comment]
Spent some time last night trying to track this down, still can't come up with anything.

Effectively for the repo case, all that is being executed is as follows, presumably across two different connections, one connection for each transaction, and all serially:

```
BEGIN TRANSACTION
DELETE FROM products AS p0
ROLLBACK TRANSACTION
BEGIN TRANSACTION
INSERT INTO products (name,tags,inserted_at,updated_at) VALUES (?,?,?,?)
DELETE FROM products AS p0
<<<<<<< error here
ROLLBACK TRANSACTION
```

One thought I had was that it was related to us not resetting statements or something, though I would presume that a `ROLLBACK` would do that for us. I tried adding a reset for the `SQLITE_DONE` case in the nif, as that is what `esqlite` does, but that did not help either.

Read through the docs here and could not find anything that stood out. https://sqlite.org/lang_transaction.html

**Comment by warmwaffles** [comment]
Yea that reset bug is actually something for an older version of sqlite3

> For all versions of SQLite up to and including 3.6.23.1, a call to sqlite3_reset() was required after sqlite3_step() returned anything other than SQLITE_ROW before any subsequent invocation of sqlite3_step(). Failure to reset the prepared statement using sqlite3_reset() would result in an SQLITE_MISUSE return from sqlite3_step(). But after version 3.6.23.1 (2010-03-26, sqlite3_step() began calling sqlite3_reset() automatically in this circumstance rather than returning SQLITE_MISUSE. This is not considered a compatibility break because any application that ever receives an SQLITE_MISUSE error is broken by definition. The SQLITE_OMIT_AUTORESET compile-time option can be used to restore the legacy behavior.

https://sqlite.org/c3ref/step.html

**Comment by kevinlang** [comment]
Unfortunately changing the `BEGIN TRANSACTION` to `BEGIN IMMEDIATE TRANSACTION` within `handle_begin` doesn't fix the problem for me - I still hit the same error.

**Comment by warmwaffles** [comment]
In the commit above, I added  overlaps for connections on the same database file.

**Comment by kevinlang** [comment]
OK I think I have a big lead here!

I added some logging, you can see where in the `kcl-busy-log` branch. I noticed that the statement ref we have during `fetch_all` for the delete statement that is similar across the two tests is the same, DESPITE the fact we are using a different database connection. So somehow a ref from a statement in connection A is being used for connection B.

```
BEGIN TRANSACTION
CONN
#Reference<0.819863025.4135452712.142559>
%Exqlite.Query{
  command: :delete,
  name: "ecto_386",
  ref: #Reference<0.819863025.4135452709.142087>,
  statement: "DELETE FROM products AS p0"
}
CONN
#Reference<0.819863025.4135452712.142559> <<<<<<<<< DIFFERENT db conn
STMT
#Reference<0.819863025.4135452709.142087> <<<<<<<<< SAME stmt ref
ROLLBACK TRANSACTION
.CONN
#Reference<0.819863025.4135452712.142559>
BEGIN TRANSACTION
CONN
#Reference<0.819863025.4135452712.142548>
%Exqlite.Query{
  command: :insert,
  name: nil,
  ref: #Reference<0.819863025.4135452709.142090>,
  statement: "INSERT INTO products (name,tags,inserted_at,updated_at) VALUES (?,?,?,?)"
}
CONN
#Reference<0.819863025.4135452712.142548>
STMT
#Reference<0.819863025.4135452709.142090>
%Exqlite.Query{
  command: :delete,
  name: "ecto_386",
  ref: #Reference<0.819863025.4135452709.142087>,
  statement: "DELETE FROM products AS p0"
}
CONN
#Reference<0.819863025.4135452712.142548> <<<<<< DIFFERENT db conn
STMT
#Reference<0.819863025.4135452709.142087> <<<<<< SAME statement ref
ROLLBACK TRANSACTION
CONN
#Reference<0.819863025.4135452712.142548>
``` 

Ran with `mix test --only busy_repo --seed 383763`

@warmwaffles

**Comment by warmwaffles** [comment]
I was just doing the same thing.


```
#Reference<0.2735281943.1181351989.197525>
  "BEGIN TRANSACTION"
#Reference<0.2735281943.1181351989.197525>
  "SAVEPOINT exqlite_savepoint"
#Reference<0.2735281943.1181351989.197525>
  "INSERT INTO accounts (name,inserted_at,updated_at) VALUES (?,?,?)"
#Reference<0.2735281943.1181351989.197525>
  "INSERT INTO users (name,inserted_at,updated_at) VALUES (?,?,?)"
#Reference<0.2735281943.1181351989.197525>
  "INSERT INTO account_users (account_id,user_id,inserted_at,updated_at) VALUES (?,?,?,?)"
#Reference<0.2735281943.1181351989.197525>
  "RELEASE SAVEPOINT exqlite_savepoint"
#Reference<0.2735281943.1181351989.197525>
  "ROLLBACK TRANSACTION"
  
#Reference<0.2735281943.1181351989.197538>
  "BEGIN TRANSACTION"
#Reference<0.2735281943.1181351989.197538>
  "SELECT u0.id, u0.name, u0.inserted_at, u0.updated_at FROM users AS u0"
#Reference<0.2735281943.1181351989.197538>
  "INSERT INTO users (name,inserted_at,updated_at) VALUES (?,?,?)"
#Reference<0.2735281943.1181351989.197538>
  "INSERT INTO users (name,inserted_at,updated_at) VALUES (?,?,?)"
```

**Comment by warmwaffles** [comment]
So it is using the same statement but for a different connection. That's really weird, so it's handing a reference from one db connection to another?

**Comment by warmwaffles** [comment]
Sounds like we resolved this then?

**Comment by kevinlang** [comment]
I'll close for now :crossed_fingers:
