### ISSUE TITLE
Allow insert_all to be called with a query instead of rows

### ISSUE THREAD

**Issue by Eiji7** [warmwaffles/exqlite#44]
Looks like `ecto` is going to support calling [Repo.insert_all/3](https://hexdocs.pm/ecto/Ecto.Repo.html#c:insert_all/3) with [Ecto.Query](https://hexdocs.pm/ecto/Ecto.Query.html) as source.

Related pull requests: elixir-ecto/ecto#3574 and elixir-ecto/ecto_sql#308

**Comment by warmwaffles** [comment]
Oh that looks like it is going to be fun. Thanks for bringing this up @Eiji7.

**Comment by warmwaffles** [comment]
@kevinlang this is going to be added soonish. We'll just need to port it over.

**Comment by warmwaffles** [comment]
Actually this looks really easy to add. I'm working on it now.
