### ISSUE TITLE
Sandbox does not recover properly from errors, leading to busy issues

### ISSUE THREAD

**Issue by kevinlang** [warmwaffles/exqlite#58]
If you go to `integration_test/exqlite/all_test.exs` and comment out the line for:

```
Code.require_file "#{ecto}/integration_test/cases/interval.exs", __DIR__
```

and run the test suite, the first test fails due to some reason, and then the rest of the tests fail with "Database busy". Which means the failed test is not rolling back its transaction correctly...

I believe `db_connection` has a `:disconnect` return status that I noticed some of the other adapters take use of when hitting errors. I think we need to use that for some of the errors we cannot recover from, so that the entire connection is closed and the database does not stay in an unreachable state until the entire application is restarted!

To be clear, this may not be scoped only to the sandbox. This probably represents an error that could occur in normal "production" application use.

**Comment by warmwaffles** [comment]
Yea I was running into this issue as well on my end of things. And do believe it could affect the production application use.

**Comment by warmwaffles** [comment]
@kevinlang do you have a reliable way to reproduce this error? We used to before we were able to get the returning clause functioning. I just want to make sure when we flip some of these `:error`'s to `:disconnect` that we have a test that reliably bombs.

**Comment by kevinlang** [comment]
Uncommenting the `type.exs` and running the integration tests reproduces it for me.

**Comment by warmwaffles** [comment]
Yea this is a hard one to track down. If we bubble back any `:disconnect` some other errors occur.
