### ISSUE TITLE
Make last_insert_id call from Exqlite skippable, or otherwise remove it

### ISSUE THREAD

**Issue by kevinlang** [warmwaffles/exqlite#83]
We no longer need it in the ecto layer thanks to `RETURNING` support added in #81. We can avoid another NIF call by not doing it when driving Exqlite via the Ecto adapter. 

We should _probably_ keep it there and configurable for those who want to use `Exqlite` (without ecto) directly. Though they should probably also just use `RETURNING` themselves too, so maybe it makes sense to cut it out all together.

**Comment by warmwaffles** [comment]
Let's leave the NIF call, as I can see that being a needed thing for someone and it will be supported by sqlite3 forever since it's been there since inception.
