### ISSUE TITLE
Test failure due to `DSQLITE_LIKE_DOESNT_MATCH_BLOBS`

### ISSUE THREAD

**Issue by kevinlang** [warmwaffles/exqlite#89]
```
assert [^id] = TestRepo.all(from(p in Post, where: like(p.blob, ^"hello"), select: p.id))
```

Will fail with RHS being empty. If I set `-DSQLITE_LIKE_DOESNT_MATCH_BLOBS=0`, it passes.

We will either want to mark those respective tests as ignore, or set this flag to 0. I notice that in https://www.sqlite.org/compile.html it recommends setting it to true, though.

What do you think, @warmwaffles ?

**Comment by warmwaffles** [comment]
I set it to true originally because of the recommendations. Which means I think we should tag those tests and then exclude them.

**Comment by kevinlang** [comment]
:+1:
