### ISSUE TITLE
Onboard migration.exs test suite

### ISSUE THREAD

**Issue by kevinlang** [warmwaffles/exqlite#95]

**Comment by warmwaffles** [comment]
The other thing that needs to be rectified is deleting the old database file before running the test suite. Sometimes it gets stored in a bad state.

```
     14:52:13.841 [warn]  You are running migration 1000649 but an older migration with version 1006275 has already run.

     This can be an issue if you have already ran 1006275 in production because a new deployment may migrate 1000649 but a rollback command would revert 1006275 instead of 1000649.

     If this can be an issue, we recommend to rollback 1000649 and change it to a version later than 1006275.
```

**Comment by warmwaffles** [comment]
This is supposed to do that but I don't know if it is actually working

```elixir
# 
#  integration_test/exqlite/test_helper.exs
#
# Load up the repository, start it, and run migrations
_ = Ecto.Adapters.Exqlite.storage_down(TestRepo.config())
:ok = Ecto.Adapters.Exqlite.storage_up(TestRepo.config())

_ = Ecto.Adapters.Exqlite.storage_down(PoolRepo.config())
:ok = Ecto.Adapters.Exqlite.storage_up(PoolRepo.config())
```

**Comment by warmwaffles** [comment]
One test caught my eye

```
EXQLITE_INTEGRATION=true mix test deps/ecto_sql/integration_test/sql/migration.exs:590
```

```
** (Exqlite.Error) near "database": syntax error
```

Query emitted

```
create database ecto_prefix_test
```

Now what this _should_ probably be is `attach database ":memory:" as foo` or `attach database "./path" as ecto_prefix_test`

Command it is failing on

```
execute TestRepo.create_prefix(@prefix)
```

**Comment by kevinlang** [comment]
Yeah that one is incorrect for sure.

One thing to note is that doing _either_ `:memory:` or a tmp path will not quite work for the `PoolRepo`, as it does not necessarily use a single connection for the duration of the test. We may need to change the tests that rely on `PoolRepo` with a `prefix` to use a `TestRepo` instead.

**Comment by warmwaffles** [comment]
I don't think we'll be able to get that test working for now. the `attach` only works for the current connection obviously so the pooled connections won't know about the other already connecting. Shame.
